---
apiVersion: v1
kind: Service
metadata:
  name: visacards-api
  labels:
    app: visacards-api
spec:
  type: NodePort
  selector:
    app: visacards-api
  ports:
    - protocol: TCP
      port: 80
      name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: visacards-api
spec:
  type: NodePort
  selector:
    matchLabels:
      app: visacards-api
  replicas: 1
  template:
    metadata:
      labels:
        app: visacards-api
    spec:
      containers:
        - name: visacards-api
          image: afonso13/visacards-api:latest
          ports:
            - name: liveness-port
              containerPort: 80
              hostPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: liveness-port
            failureThreshold: 1
            periodSeconds: 60
            # Override pod-level terminationGracePeriodSeconds #
            terminationGracePeriodSeconds: 60